"""empty message

Revision ID: 50a71411928a
Revises: abd66e40d8bd
Create Date: 2021-02-24 15:58:34.497802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a71411928a'
down_revision = 'abd66e40d8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('done', table_name='todo')
    op.drop_index('label', table_name='todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('label', 'todo', ['label'], unique=True)
    op.create_index('done', 'todo', ['done'], unique=True)
    # ### end Alembic commands ###
